# Generated by Django 5.1.2 on 2024-10-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            insert into store_collection (title)
            values ('collection1');
        """, """
        delete from store_collection
        where title = 'collection1';
        """)
    ]
